parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
env:
  node: true
  es2021: true
extends:
  - airbnb-base
